fosterapp/urls.py
from django.conf.urls import url
from fosterapp import views

app_name = 'fosterapp'

urlpatterns=[
    url(r'^register/$',views.register,name='register'),
    url(r'^user_login/$',views.user_login,name='user_login'),
]

fosterpetproj/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from fosterapp import views
from django.views.static import serve
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',views.index,name='index'),
    url(r'^special/',views.special,name='special'),
    url(r'^fosterapp/',include('fosterapp.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^about/$', views.about, name='about'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^services/$', views.services, name='services'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^carousel/$', views.carousel, name='carousel'),
    url('avatar/', include('avatar.urls')),
]

urlpatterns += staticfiles_urlpatterns()
if settings.DEBUG:
		urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
		urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fosterapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfileInfo(models.Model):
	user = models.OneToOneField(User,on_delete=models.CASCADE)
	portfolio_site = models.URLField(blank=True)
	profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

	def __str__(self):
		return self.user.username

fosterapp/forms.py
from django import forms
from fosterapp.models import UserProfileInfo
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput())

	class Meta():
		model = User
		fields = ('first_name', 'last_name', 'username','password','email')

class UserProfileInfoForm(forms.ModelForm):
	class Meta():
		model = UserProfileInfo
		fields = ('portfolio_site','profile_pic')

fosterapp/views.py
from django.shortcuts import render
from fosterapp.forms import UserForm,UserProfileInfoForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

def index(request):
    return render(request,'fosterapp/index.html')
	
@login_required
def special(request):
    return HttpResponse("You are logged in !")
	
@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))
	
def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            if 'profile_pic' in request.FILES:
                print('found it')
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()
            registered = True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    return render(request,'fosterapp/registration.html',
                          {'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered})
						   
def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Your account was inactive.")
        else:
            myMessage = 'You have enterred a wrong login details'
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return render(request, 'fosterapp/index.html', {'myMessage': myMessage})
            # return HttpResponse("Invalid login details given")
    else:
        return render(request, 'fosterapp/login.html', {})


def about(request):
	return render(request, 'fosterapp/about.html', {})

def contact(request):
	if request.method == 'POST':
		email = request.POST['email']
		fullName = request.POST['fullName']
		coyName = request.POST['coyName']
		messegeArea = request.POST['messegeArea']

	return render(request, 'fosterapp/contact.html', {})

def services(request):
	return render(request, 'fosterapp/services.html', {})

@login_required
def profile(request):
    return render(request, 'fosterapp/profile.html')


def carousel(request):
    return render(request, 'fosterapp/carousel.html', {})

templates/fosterapp/about.html
{% extends 'fosterapp/base.html' %}
{% load static %}

{% block content %}
      
      
      <div class="jumbotron jumbotron-fluid" style="background-image: url({% static 'img/factory-2254981_1920.jpg' %}); background-size: cover; height: 400px">
          <div class="text-center" style="margin-top: 120px;">
            <span class="display-4 font-weight-bold text-light bg-danger">About Us</span>
          </div>
      </div>
      
      <div class="container">
        <div class="row">
            <div class="col-lg col-md bg-light">
                <p class="text-justify p-3" id="aboutText">
                    Foster Oil &amp; Gas Limited was incorporated in 2016 as an indigenous petroleum development company with a reputation of and  gas exploration and production activities, refining, commercialization and transportation of petrochemical products
                    Anchored on an experienced and hard-working professional team with advent technology and harmonious community relations, we strive to achieve the desired goals and stand tall in the oil and gas industry.
                </p>
                <p id="aboutText">
                    Foster is safety conscious and adhered to quality health safety and environment duty, standardising all  into operations
                </p>
                <p id="aboutText">
                    We aspire to be the pacesetters for corporate social responsibility in Nigeria, hence, our initiative of giving back more than what we take to attract and retains the goodwill of our host communities will intentionally mitigate social roles and optimise production which is the hallmark of any oil and Gas business
                </p>
            </div>
            <div class="col-lg col-md bg-light pr-0">
                <img src="{% static 'img/chad-peltola-d1lHAcrJ1v0-unsplash.jpg' %}" class="img-responsive" style="width: 100%;">
            </div>
          </div>
      </div>
      
      
{% endblock %}

templates/fosterapp/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    
    <link rel="icon" type="favicon" href="{% static 'img/fosteroilgas_d200.svg' %}">
      
    <!-- Google font -->
    <link href="https://fonts.googleapis.com/css2?family=Rajdhani:wght@600&family=Yanone+Kaffeesatz&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Comic+Neue&display=swap" rel="stylesheet"> 
      
    <!--Link to enternal stylesheet -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

    <title>Foster Petroleum Development Company Ltd.</title>
  </head>
  <body>
    <!-- Navigation manu starts here -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
        <img src="{% static 'img/fosteroilgas_new.svg' %}" class="imgId" alt="fosterpetroleum_logo" onclick="Redir();">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'index' %}">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'about' %}">About</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Services
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'services' %}">Oil &amp; Gas</a>
              <a class="dropdown-item" href="{% url 'services' %}">Refining</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'services' %}">Products</a>
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'contact' %}">Contact</a>
          </li>
          </ul>
          <ul class="navbar-nav ml-auto">
          </li>     
          {# Some logic on what to display for last item#}
          {% load avatar_tags %}
          {% if user.is_authenticated %}
            <li class="nav-item"><a class="nav-link" href="{% url 'profile' %}">{% avatar user 40 class="rounded-circle img-responsive" id="user_avatar" %}</a></li>
            <li class="nav-item"><a class="nav-link text-capitalize text-success font-weight-bold rounded-pill" href="{% url 'profile' %}">{{ user.username }}</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'admin:index' %}">Admin</a></li>
            <li class="nav-item"><a class="nav-link text-danger" href="https://emailmg.ipage.com/roundcube/" target="_blank">Webmail</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li class="nav-item"><a class="nav-link" href="{% url 'fosterapp:register' %}">Register</a>
            <li class="nav-item"><a class="nav-link" href="{% url 'fosterapp:user_login' %}">Login</a></li>
          {% endif %}
        </ul>
        <!-- <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form> -->
      </div>
      </nav>
    <!-- Navigation manu ends here -->

    {% block content %}

    {% endblock %}



 <!-- Footer starts here -->
      <footer class="container-fluid bground-success" style="margin-top: 200px;">
        <div class="p-3">
            <p class="text-center text-light">Copyright &copy; <script>var timeNow = new Date().getFullYear(); document.write(timeNow);</script>  - All rights reserved</p>
        </div>
      </footer>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script>
      <!--
      function Redir() {
        window.location = "{% url 'index' %}";
      }
      //-->
    </script>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

templates/fosterapp/carousel.html
{% extends 'fosterapp/base.html' %}
{% load static %}
{% block content %}
<!--Carousel Starts here -->
      <div class="jumbotron jumbotron-fluid">
        <div id="carouselExampleFade" class="carousel slide carousel-fade" data-ride="carousel">
          <div class="carousel-inner">
            <div class="carousel-item active">
              <img src="{% static 'img/oil-port-1785693_1280.jpg' %}" class="d-block -100" alt="foster_slide_1">
            </div>
            <div class="carousel-item">
              <img src="{% static 'img/bitmap_2.png' %}" class="d-block img-responsive" style="width: 100%; height: 100%;" alt="foster_slide_2">
            </div>
            <div class="carousel-item">
              <img src="{% static 'img/bitmap_3.png' %}" class="d-block w-100" alt="foster_slide_3">
            </div>
          </div>
          <a class="carousel-control-prev" href="#carouselExampleFade" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleFade" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
      </div>
      <!-- Carousel Starts here -->
      <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
          <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
          <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img src="{% static 'img/oil-port-1785693_1280.jpg' %}" class="d-block w-100" alt="...">
            <div class="carousel-caption d-none d-md-block">
              <h5>First slide label</h5>
              <p>Nulla vitae elit libero, a pharetra augue mollis interdum.</p>
            </div>
          </div>
          <div class="carousel-item">
            <img src="{% static 'img/bitmap_2.png' %}" class="d-block w-100" alt="...">
            <div class="carousel-caption d-none d-md-block">
              <h5>Second slide label</h5>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
            </div>
          </div>
          <div class="carousel-item">
            <img src="{% static 'img/bitmap_3.png' %}" class="d-block w-100" alt="...">
            <div class="carousel-caption d-none d-md-block">
              <h5>Third slide label</h5>
              <p>Praesent commodo cursus magna, vel scelerisque nisl consectetur.</p>
            </div>
          </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
      <!--Carousel Ends here -->

  {% endblock %}

templates/fosterapp/contact.html
{% extends 'fosterapp/base.html' %}
{% load static %}

{% block content %}

      
      <div class="jumbotron jumbotron-fluid" style="background-image: url({% static 'img/factory-2254981_1920.jpg' %}); background-size: cover; height: 400px">
          <div class="text-center" style="margin-top: 120px;">
            <span class="display-4 font-weight-bold text-light bg-danger">Contact Us</span>
          </div>
      </div>
      
      <div class="container">
        <div class="row">
            <div class="col-lg col-md bg-light">
                <h3>GET IN TOUCH WITH US!</h3>
                YOUR EMAIL ADDRESS WILL NOT BE PUBLISHED.
               <form method="post" action="{% url 'contact' %}">
                  {% csrf_token %}
                  <div class="form-group">
                    <label for="exampleInputEmail1">Email address</label>
                    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="email" placeholder="example@hostname.com">
                    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
                  </div>
                  <div class="form-group">
                    <label for="exampleInputFullName">Full Name</label>
                    <input type="text" class="form-control" id="exampleInputFullName" name="fullName">
                  </div>
                  <div class="form-group">
                    <label for="exampleInputCompanyName">Company Name</label>
                    <input type="text" class="form-control" id="exampleInputCompanyName" name="coyName">
                  </div>
                  <div class="form-group">
                    <label for="exampleInputCompanyName">Type your messages here</label>
                    <textarea type="textarea" rows="4" class="form-control" id="exampleInputCompanyName" name="messegeArea"></textarea>
                  </div>
            
                  <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
            <div class="col-lg col-md bg-light pr-0">
                <h3 class="contactClassH">CONTACT INFORMATION</h3>
                <p class="contactClass">
                CALL US AT ANY TIME!<br>
                Address:<br>

                #5 Enwuchukwa Close, off Geodetic Road,<br> Beside Shell IA, Rumuobiakani,<br> Port Harcourt
                Rivers State, Nigeria<br>

                Telephone:<br>
                (234) 803-0856-544<br>

                Fax:<br>
                (234) 701-5858-088<br>

                Email Us:<br>
                info@fosterlimited.com
              </p>
            </div>
          </div>
      </div>
      
      
{% endblock %}

templates/fosterapp/home.html
{% extends "fosterapp/base.html" %}
{% block body_block %}
<div class="container">
  <div class="jumbotron">
    <h1>Welcome to the Djungle !</h1>
    {% if user.is_authenticated %}
        <h2>Hello {{ user.username }}</h2>
    {% else %}
        <h2>Register or Login if you'd like to</h2>
    {% endif %}
  </div>
</div>
{% endblock %}

templates/fosterapp/index.html
{% extends 'fosterapp/base.html' %}
{% load static %}

{% block content %}
      
      <!-- <div class="jumbotron jumbotron-fluid mb-5" style="background-image: url({% static 'img/oil-rig-514035_1920.jpg' %}); background-size: cover;" id="bgimgId">
          <div class="text-center mt-5">
            {% if user.is_authenticated %}
                <h2 class="text-light font-weight-bold"></h2>
            {% else %}
                    <h2 class="text-center text-light" style="padding-top: -20px;"><i class="bg-danger">{{ myMessage }}</i></h2>
            {% endif %}
          </div>
          <div class="text-center" style="margin-top: 200px;">
            <span class="coyTxt1">Foster Petroleum</span><br><br>
            <span class="coyTxt2">Development Company Limited</span>
          </div>
      </div> -->
      <!--Carousel Starts here -->
      <div class="mb-5">
        <div id="carouselExampleFade" class="carousel slide carousel-fade" data-ride="carousel">
          <div class="carousel-inner">
            <div class="carousel-item active">
              <img src="{% static 'img/foster_slider_1.svg' %}" class="d-block w-100" alt="foster_slide_1">
            </div>
            <div class="carousel-item">
              <img src="{% static 'img/foster_slider_2.svg' %}" class="d-block w-100" alt="foster_slide_2">
            </div>
            <div class="carousel-item">
              <img src="{% static 'img/foster_slider_3.svg' %}" class="d-block w-100" alt="foster_slide_3">
            </div>
          </div>
          <a class="carousel-control-prev" href="#carouselExampleFade" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleFade" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
      </div>
      <!--Carousel Ends here -->
      <div class="container">
        <div class="row">
            <div class="col-lg col-md bg-light mr-3">
                <img src="{% static 'img/foster_oil_xploration.png' %}" class="mr-0 p-0" style="width: 100%;">
                <h4 class="text-center p-3 text-danger">Oil &amp; Gas Exploration</h4>
                <p class="text-justify">
                    The role of exploration is to provide the information required to exploit the best opportunities presented in the choice of areas, and to manage research operations on the acquired blocks.
                </p>
            </div>
            <div class="col-lg col-md bg-light mr-3">
                <img src="{% static 'img/foster_production.png' %}" class="img-responsive" style="width: 100%;">
                <h4 class="text-center p-3 text-danger">Production</h4>
                <p class="text-justify">
                    The oil and gas sector is facing a number of sector-internal challenges, including shortage of skilled workers, accessing oil and gas reserves in geographically remote areas, promoting occupational safety and health standards, and respect for the fundamental principles and rights at work.
                </p>
            </div>
            <div class="col-lg col-md bg-light">
                <img src="{% static 'img/foster_oil_refining.jpg' %}" class="" style="width: 100%;">
                <h4 class="text-center p-3 text-danger">Refining</h4>
                <p class="text-justify">
                    We stand to give advice and ubiquitous solutions to our clients, by prescribing, procuring, installing and managing our clients' oil, gas and petrochemical products.
                </p>
            </div>
        </div>
      </div>
      
      <!-- About US Section -->
      <div class="jumbotron jumbotron-fluid bground-success mt-5">
          <div class="text-center container">
            <h2 class="text-light text-uppercase">About Us</h2>
            <p class="text-light text-justify" id="aboutUs">
                Foster Petroleum Development Limited was incorporated in 2019 as an indigenous petroleum development company with a reputation of and  gas exploration and production activities, refining, commercialization and transportation of petrochemical products Anchored on an experienced and hard-working professional team with advent technology and harmonious community relations, we strive to achieve the desired goals and stand tall in the oil and gas industry.
                Foster is safety conscious and adhered to quality health safety and environment duty, standardising all  into operations
                We aspire to be the pacesetters for corporate social responsibility in Nigeria, hence, our initiative of giving back more than what we take to attract and retains the goodwill of our host communities will intentionally mitigate social roles and optimise production which is the hallmark of any oil and Gas business
            </p>
          </div>
      </div>
      
      <!-- Contact info starts here -->
      <div class="container">
          <div class="row">
            <div class="col-lg col-md border border-light rounded mr-3 p-3 bg-light">
              <div class="text-center">
                <img src="{% static 'img/call-24px.svg' %}" alt="foster_call" class="p-3">
                  <h3 class="text-danger">CALL US NOW!</h3>
                    <p>(234)-803-0856-544</p>
                    <span class="font-weight-bold">We'll be happy to answer any questions.</span>
              </div>
            </div>
            <div class="col-lg col-md border border-light rounded mr-3 p-3 bg-light">
              <div class="text-center">
                <img src="{% static 'img/schedule-24px.svg' %}" alt="foster_call" class="p-3">
                <h3 class="text-danger">HOURS OF OPERATION</h3>
                <p>
                    Monday: Friday 7:30 am - 18:30 pm
                    Saturday: 11:30 am - 17:00 pm
                  </p>
              </div>
            </div>
            <div class="col-lg col-md border border-light rounded p-3 bg-light">
              <div class="text-center">
                <img src="{% static 'img/location_on-24px.svg' %}" alt="foster_call" class="p-3">
                <h3 class="text-danger">LOCATION</h3>
                <p>
                    #5 Enwuchukwa Close, off Geodetic Road, Beside Shell IA, Rumuobiakani, Port Harcourt
                    Rivers State, Nigeria
                  </p>
              </div>
            </div>
          </div>
      </div>
      
{% endblock %}

templates/fosterapp/login.html
{% extends 'fosterapp/base.html' %}
{% load crispy_forms_tags %}
{% block content %}

  <div class="container">
    <div class="jumbotron" style="margin-top: 120px;">
      <h1>Login here :</h1>
<form method="post" action="{% url 'fosterapp:user_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">
<label for="password">Password:</label>
          <input type="password" name="password" placeholder="Password">
<input type="submit" name="" value="Login">
</form>
</div>
  </div>
  
{% endblock %}

templates/fosterapp/profile.html
{% extends 'fosterapp/base.html' %}
{% load static %}

{% block content %}
	<div class="jumbotron" style="margin-top: 120px;">
		{% load avatar_tags %}
		{% if user.is_authenticated %}
			<h1 class="text-center text-uppercase mb-5">Dear {{ user.first_name }}, below is your Profile Details</h1>
			<table class="table">
			  <thead class="thead-dark">
			    <tr>
			      <th scope="col">First Name</th>
			      <th scope="col">Last Name</th>
			      <th scope="col">Username</th>
			      <th scope="col">Email Address</th>
			      <th scope="col">Profile Picture</th>
			    </tr>
			  </thead>
			  <tbody>
			    <tr>
			      <td>{{ user.first_name }}</td>
			      <td>{{ user.last_name }}</td>
			      <td>{{ user.username }}</td>
			      <td>{{ user.email }}</td>
			      <td>{% avatar user 50 class="rounded-circle" id="user_avatar" %} <a href="{% url 'avatar_change' %}">Change your avatar</a></td>
			    </tr>
			  </tbody>
			</table>
		{% endif %}
	</div>

{% endblock %}

templates/fosterapp/registration.html
{% extends "fosterapp/base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

  <div class="container">
    <div class="jumbotron" style="margin-top: 120px;">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h1>Register Here</h1>
        <h3>Just fill out the form.</h3>
<form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form | crispy }}
          {{ profile_form | crispy}}
          <input type="submit" name="" value="Register">
        </form>
        
      {% endif %}
    </div>
  </div>
  
{% endblock %}